### ISSUE TITLE
有so吗

### ISSUE THREAD

**Issue by dosillee** [leonsimple/Android_Silk_encode_and_decode#1]
不知为啥编不出来，能上传个so吗

**Comment by shuaiyinoo** [comment]
真的非常感谢 回馈开源 心路历程

1.首先建立一个JNI的文件夹 引入作者文件夹下面的JNI （全部拷贝进去）

2.File->Project Structure ->里面配置NDK的路径（这个时候编译可能会报错 可能NDK是AS自动下载的）
去这里 https://developer.android.com/ndk/downloads/ 下载最新的NDK 我的是MAC下载
android-ndk-r16b-darwin-x86_64.zip这个文件

3.把 toolchains 文件夹下面的东西 全部拷贝的AS自动下载的NDK下面的toolchains 文件夹下

4.在包名下面建立 Jni 文件
public class Jni {
    static {
        System.loadLibrary("silk");
    }
    public static native int decode(String org, String dest);
    public static native int encode(String org, String dest);
}

5.接下来就是修改文件了
build.gradle 下面加入
ndk {
            moduleName "x"
            abiFilters 'x86','armeabi-v7a'
            ldLibs "log"
        }

externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }

6.CMakeLists.txt文件修改
project(自己APP包名)
add_executable(自己APP包名 ${SOURCE_FILES})

7.decoder.cpp文件修改
const char *tmp = "/data/data/包名/t.t";（注意这里是包名用.分割）
jclass clazz = env->FindClass("包名(用/分割)/Jni"); 这里是调用第4步建立的Jni文件（注意这里用/分割）

8.在需要的时候调用 解码
String amrPath = "/storage/emulated/0/xxx.amr";
String mp3Path = "/storage/emulated/0/xxx.mp3";
Jni.decode(amrPath, mp3Path);

9.助你好运

10.还不知道加我微信shuaiyinoo 备注GitHub Android_Silk

**Comment by dosillee** [comment]
非常感谢回复，已经搞定了。赞发自我的华为手机-------- 原始邮件 --------主题：Re: [leonsimple/Android_Silk_encode_and_decode] 有so吗 (#1)发件人：帅印 收件人：leonsimple/Android_Silk_encode_and_decode 抄送：张凌波 ,Author 真的非常感谢 回馈开源 心路历程
1.首先建立一个JNI的文件夹 引入作者文件夹下面的JNI （全部拷贝进去）
2.File->Project Structure ->里面配置NDK的路径（这个时候编译可能会报错 可能NDK是AS自动下载的）
去这里 https://developer.android.com/ndk/downloads/ 下载最新的NDK 我的是MAC下载
android-ndk-r16b-darwin-x86_64.zip这个文件
3.把 toolchains 文件夹下面的东西 全部拷贝的AS自动下载的NDK下面的toolchains 文件夹下
4.在包名下面建立 Jni 文件
public class Jni {
static {
System.loadLibrary("silk");
}
public static native int decode(String org, String dest);
public static native int encode(String org, String dest);
}
5.接下来就是修改文件了
build.gradle 下面加入
ndk {
moduleName "x"
abiFilters 'x86','armeabi-v7a'
ldLibs "log"
}
externalNativeBuild {
ndkBuild {
path 'src/main/jni/Android.mk'
}
}
6.CMakeLists.txt文件修改
project(自己APP包名)
add_executable(自己APP包名 ${SOURCE_FILES})
7.decoder.cpp文件修改
const char *tmp = "/data/data/包名/t.t";（注意这里是包名用.分割）
jclass clazz = env->FindClass("包名(用/分割)/Jni"); 这里是调用第4步建立的Jni文件（注意这里用/分割）
8.在需要的时候调用 解码
String amrPath = "/storage/emulated/0/xxx.amr";
String mp3Path = "/storage/emulated/0/xxx.mp3";
Jni.decode(amrPath, mp3Path);
9.助你好运
10.还不知道加我微信shuaiyinoo 备注GitHub Android_Silk

**Comment by shuaiyinoo** [comment]
so不知道在哪里 好像是动态引用的

**Comment by dosillee** [comment]
so文件在build\intermediates\ndkBuild里

**Comment by leonsimple** [comment]
👍
